app:
  scheduler:
    enable: false
    interval: 10s
    force-check-delay: 10s

clients:
  github:
    base-url: https://api.github.com/
  stack-overflow:
    base-url: https://api.stackexchange.com/
  bot:
    base-url: http://localhost:8090/

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scrapper?autosave=always
    username: postgres
    password: postgres

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
