app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  jdbc:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres

clients:
  github:
    base-url: https://api.github.com/
  stack-overflow:
    base-url: https://api.stackexchange.com/
  bot:
    base-url: http://localhost:8090/

spring:
  application:
    name: scrapper
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
