app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  database-access-type: jpa

clients:
  github:
    base-url: https://api.github.com/
    backoff:
      type: exponential
      min-backoff: 1s
      max-attempts: 10
      codes: 500
  stack-overflow:
    base-url: https://api.stackexchange.com/
    backoff:
      type: exponential
      min-backoff: 1s
      max-attempts: 10
      codes: 500
  bot:
    base-url: http://localhost:8090/
    backoff:
      type: exponential
      min-backoff: 1s
      max-attempts: 10
      codes: 500

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      strategy: all
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"Лимит запросов исчерпан\" }"
      rate-limits:
        - cache-key: getHeader('X-Forwarded-For')
          bandwidths:
            - capacity: 100
              time: 1
              unit: minutes
            - capacity: 50
              time: 30
              unit: seconds

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
