/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq.enums;


import edu.java.scrapper.domain.jooq.Public;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum ExternalService implements EnumType {

    GitHub("GitHub"),

    StackOverflow("StackOverflow");

    private final String literal;

    private ExternalService(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "external_service";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static ExternalService lookupLiteral(String literal) {
        return EnumType.lookupLiteral(ExternalService.class, literal);
    }
}
