app:
  telegram-token: ${TELEGRAM_TOKEN:unset}
  scrapper-topic:
    name: updates
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    topics:
      updates:
        name: updates
      dlq:
        name: updates_dlq
        replicas: 10
        partitions: 1

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  config:
    import: optional:file:.env[.properties]
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      strategy: all
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"Лимит запросов исчерпан\" }"
      rate-limits:
        - cache-key: getHeader('X-Forwarded-For')
          bandwidths:
            - capacity: 100
              time: 1
              unit: minutes
            - capacity: 50
              time: 30
              unit: seconds

clients:
  scrapper:
    base-url: http://localhost:8080/
    backoff:
      type: exponential
      min-backoff: 1s
      max-attempts: 10
      codes: 500

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
