/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq.tables.pojos;


import edu.java.scrapper.domain.jooq.enums.ExternalService;

import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * The links that are being scrapped
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Links implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String url;
    private ExternalService service;
    private OffsetDateTime lastUpdate;

    public Links() {}

    public Links(Links value) {
        this.id = value.id;
        this.url = value.url;
        this.service = value.service;
        this.lastUpdate = value.lastUpdate;
    }

    @ConstructorProperties({ "id", "url", "service", "lastUpdate" })
    public Links(
        @Nullable Long id,
        @NotNull String url,
        @NotNull ExternalService service,
        @NotNull OffsetDateTime lastUpdate
    ) {
        this.id = id;
        this.url = url;
        this.service = service;
        this.lastUpdate = lastUpdate;
    }

    /**
     * Getter for <code>public.links.id</code>.
     */
    @Nullable
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.links.id</code>.
     */
    public void setId(@Nullable Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.links.url</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public String getUrl() {
        return this.url;
    }

    /**
     * Setter for <code>public.links.url</code>.
     */
    public void setUrl(@NotNull String url) {
        this.url = url;
    }

    /**
     * Getter for <code>public.links.service</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public ExternalService getService() {
        return this.service;
    }

    /**
     * Setter for <code>public.links.service</code>.
     */
    public void setService(@NotNull ExternalService service) {
        this.service = service;
    }

    /**
     * Getter for <code>public.links.last_update</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public OffsetDateTime getLastUpdate() {
        return this.lastUpdate;
    }

    /**
     * Setter for <code>public.links.last_update</code>.
     */
    public void setLastUpdate(@NotNull OffsetDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Links other = (Links) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.url == null) {
            if (other.url != null)
                return false;
        }
        else if (!this.url.equals(other.url))
            return false;
        if (this.service == null) {
            if (other.service != null)
                return false;
        }
        else if (!this.service.equals(other.service))
            return false;
        if (this.lastUpdate == null) {
            if (other.lastUpdate != null)
                return false;
        }
        else if (!this.lastUpdate.equals(other.lastUpdate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.url == null) ? 0 : this.url.hashCode());
        result = prime * result + ((this.service == null) ? 0 : this.service.hashCode());
        result = prime * result + ((this.lastUpdate == null) ? 0 : this.lastUpdate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Links (");

        sb.append(id);
        sb.append(", ").append(url);
        sb.append(", ").append(service);
        sb.append(", ").append(lastUpdate);

        sb.append(")");
        return sb.toString();
    }
}
