/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq;


import edu.java.scrapper.domain.jooq.tables.Databasechangelog;
import edu.java.scrapper.domain.jooq.tables.Databasechangeloglock;
import edu.java.scrapper.domain.jooq.tables.FollowingLinks;
import edu.java.scrapper.domain.jooq.tables.Links;
import edu.java.scrapper.domain.jooq.tables.Users;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * Provides many-to-many relation between links and users
     */
    public static final FollowingLinks FOLLOWING_LINKS = FollowingLinks.FOLLOWING_LINKS;

    /**
     * The links that are being scrapped
     */
    public static final Links LINKS = Links.LINKS;

    /**
     * Users' (or chats', it's the same) telegram ids
     */
    public static final Users USERS = Users.USERS;
}
